    [server]
    url          = "http://103.143.40.175:8081/zogsoolSdkService"
    token        = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NWM1NzUyMWE4YTRhZWJjMWQ2NWIwNSIsIm5lciI6IkNBZG1pbiIsImJhaWd1dWxsYWdpaW5JZCI6IjY5NWM1NzUxMWE4YTRhZWJjMWQ2NWIwMiIsImlhdCI6MTc3NTM5NzUxN30.VTPqXUz8RKMm_YGP12kxNWpsRlIqT4tjPiXvzEBVrHs"
    barilgiinId  = "695c57511a8a4aebc1d65b03"
    timeout_secs = 30
    retry_count  = 3

    [sdk]
    username                = "admin"
    heartbeat_interval_secs = 30
    connect_timeout_ms      = 5000
    max_connect_retries     = 5
    port                    = 37777
    org_name = "Homeplaza"
    company_name = "ParkEase"

    [[cameras]]
    ip       = "192.168.1.21"
    password = "admin123"
    http_port = 443
    gate = "entrance"
    sambar_type = "sambar"

    
