    [server]
    url          = "http://103.143.40.230:8081/zogsoolSdkService"
    token        = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWJjMjI1MTAyMjhhNzQ1NGJkZjVlZCIsIm5lciI6ItCc0LDRgNCz0LDQtCDRiNC40LvRgtCz0Y3RjdC9INGC0LHQsSIsImJhaWd1dWxsYWdpaW5JZCI6IjY4YWJjMjI0MTAyMjhhNzQ1NGJkZjVlOSIsImlhdCI6MTc3Mzg4NjY4N30.o7DKGakJFkCVvkCFobTT737BIGf5rdi3yB6Az6L3duk"
    barilgiinId  = "68abc22410228a7454bdf5ea"
    timeout_secs = 30
    retry_count  = 3

    [sdk]
    username                = "admin"
    heartbeat_interval_secs = 30
    connect_timeout_ms      = 5000
    max_connect_retries     = 5
    port                    = 37777
    org_name = "Grand Plaza"
    company_name = "ParkEase"

    [[cameras]]
    ip       = "192.168.1.110"
    password = "admin123"
    http_port = 80
    gate = "entrance"
    [[cameras]]
    ip       = "192.168.1.109"
    password = "admin123"
    http_port = 80
    gate = "entrance"
    [[cameras]]
    ip       = "192.168.1.108"
    password = "admin123"
    http_port = 80
    gate = "exit"
    [[cameras]]
    ip       = "192.168.1.111"
    password = "admin123"
    http_port = 80
    gate = "exit"




